const chordSystem = {
  C: {
    C: ["C", "C/E", "C/G"],
    Dm: ["Dm", "Dm/F", "Dm/A"],
    Em: ["Em", "Em/G", "Em/B"],
    F: ["F", "F/A", "F/C"],
    G: ["G", "G/B", "G/D"],
    Am: ["Am", "Am/C", "Am/E"],
    Bdim: ["Bdim", "Bdim/D", "Bdim/F"],
  },
  "C#": {
    "C#": ["C#", "C#/F", "C#/G#"],
    "D#m": ["D#m", "D#m/F#"],
    Fm: ["Fm", "Fm/G#"],
    "F#": ["F#", "F#/A#"],
    "G#": ["G#", "G#/C"],
    "A#m": ["A#m", "A#m/C#"],
    Cdim: ["Cdim"],
  },
  Db: {
    Db: ["Db", "Db/F", "Db/Ab"],
    Ebm: ["Ebm", "Ebm/Ab"],
    Fm: ["Fm", "Fm/Ab"],
    Gb: ["Gb", "Gb/Bb"],
    Ab: ["Ab", "Ab/C"],
    Bbm: ["Bbm", "Bbm/Db"],
    Cdim: ["Cdim"],
  },
  D: {
    D: ["D", "D/F#", "D/A"],
    Em: ["Em", "Em/A"],
    "F#m": ["F#m", "F#m/A"],
    G: ["G", "G/B"],
    A: ["A", "A/C#"],
    Bm: ["Bm", "Bm/D"],
    "C#dim": ["C#dim"],
  },
  "D#": {
    "D#": ["D#", "D#/G", "D#/A#"],
    Fm: ["Fm", "Fm/A#"],
    "F#m": ["F#m", "F#m/A#"],
    "G#": ["G#", "G#/C#"],
    "A#": ["A#", "A#/D#"],
    Cm: ["Cm", "Cm/D#"],
    Ddim: ["Ddim"],
  },
  E: {
    E: ["E", "E/G#", "E/B"],
    "F#m": ["F#m", "F#m/B"],
    "G#m": ["G#m", "G#m/B"],
    A: ["A", "A/C#"],
    B: ["B", "B/E"],
    "C#m": ["C#m", "C#m/E"],
    "D#dim": ["D#dim"],
  },
  F: {
    F: ["F"],
    Gm: ["Gm"],
    Am: ["Am"],
    Bb: ["Bb"],
    C: ["C"],
    Dm: ["Dm"],
    Edim: ["Edim"],
  },
  "F#": {
    "F#": ["F#"],
    "G#m": ["G#m"],
    "A#m": ["A#m"],
    B: ["B"],
    "C#": ["C#"],
    "D#m": ["D#m"],
    Fdim: ["Fdim"],
  },
  Gb: {
    Gb: ["Gb"],
    Abm: ["Abm"],
    Bbm: ["Bbm"],
    B: ["B"],
    Db: ["Db"],
    Ebm: ["Ebm"],
    Fdim: ["Fdim"],
  },
  G: {
    G: ["G"],
    Am: ["Am"],
    Bm: ["Bm"],
    C: ["C"],
    D: ["D"],
    Em: ["Em"],
    "F#dim": ["F#dim"],
  },
  "G#": {
    "G#": ["G#"],
    "A#m": ["A#m"],
    Cm: ["Cm"],
    "C#": ["C#"],
    "D#": ["D#"],
    Fm: ["Fm"],
    Gdim: ["Gdim"],
  },
  Ab: {
    Ab: ["Ab"],
    Bbm: ["Bbm"],
    Cm: ["Cm"],
    Db: ["Db"],
    Eb: ["Eb"],
    Fm: ["Fm"],
    Gdim: ["Gdim"],
  },
  A: {
    A: ["A"],
    Bm: ["Bm"],
    "C#m": ["C#m"],
    D: ["D"],
    E: ["E"],
    "F#m": ["F#m"],
    "G#dim": ["G#dim"],
  },
  "A#": {
    "A#": ["A#"],
    Cm: ["Cm"],
    Dm: ["Dm"],
    "D#": ["D#"],
    F: ["F"],
    Gm: ["Gm"],
    Adim: ["Adim"],
  },
  Bb: {
    Bb: ["Bb"],
    Cm: ["Cm"],
    Dm: ["Dm"],
    Eb: ["Eb"],
    F: ["F"],
    Gm: ["Gm"],
    Adim: ["Adim"],
  },
  B: {
    B: ["B"],
    "C#m": ["C#m"],
    "D#m": ["D#m"],
    E: ["E"],
    "F#": ["F#"],
    "G#m": ["G#m"],
    "A#dim": ["A#dim"],
  },
  Numbers: {
    1: ["1", "1/3", "1/5"],
    2: ["2m", "2m/4", "2m/6"],
    3: ["3m", "3m/5", "3m/7"],
    4: ["4", "4/6", "4/1"],
    5: ["5", "5/7", "5/2"],
    6: ["6m", "6m/1", "6m/3"],
    7: ["7dim", "7dim/2", "7dim/4"],
  },
  C: {
    C: ["C", "C/E", "C/G"],
    Dm: ["Dm", "Dm/F", "Dm/A"],
    Em: ["Em", "Em/G", "Em/B"],
    F: ["F", "F/A", "F/C"],
    G: ["G", "G/B", "G/D"],
    Am: ["Am", "Am/C", "Am/E"],
    Bdim: ["Bdim", "Bdim/D", "Bdim/F"],
  },
};
